FROM python:3.9-slim
EXPOSE 8008
WORKDIR /billing_api

RUN apt-get update && apt-get --yes upgrade

COPY ./requirements /billing_api/requirements
RUN pip install -r /billing_api/requirements/billing-api.txt --no-cache-dir

COPY ./billing_api /billing_api

CMD sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8008 --reload