FROM python:3.9-slim
WORKDIR /scheduler

RUN apt-get update && apt-get --yes upgrade

COPY ./requirements/scheduler.txt /scheduler/requirements/
RUN pip install -r /scheduler/requirements/scheduler.txt --no-cache-dir

COPY ./scheduler /scheduler

CMD python main.py