version: "3.9"  # optional since v1.27.0
services:
  db:
    image: "postgres:13"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_vol:/var/lib/comparing/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  etl_sqlite_pg:
    build: sqlite_to_postgres
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - dbname=${DB_NAME}
      - db_user=${DB_USER}
      - db_password=${DB_PASSWORD}
      - db_host=db
      - db_port=5432
      - sqlite_file=${SQLITE_FILE}
      - batch_size=${BATCH_SIZE}

  admin_pannel:
    build: admin_pannel
    volumes:
      - ./admin_pannel/static:/admin_pannel/static
    depends_on:
      db:
        condition: service_healthy
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DATABASE_URL: psql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    expose:
      - "8000"
    ports:
      - "8000:8000"

volumes:
  db_vol: { }