# Generated by Django 3.2.6 on 2021-08-20 04:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(verbose_name='name')),
                ('period', models.DurationField(verbose_name='period')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionFilm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('film_id', models.TextField(verbose_name='film_id')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription', verbose_name='sub_id')),
            ],
        ),
    ]
