# Generated by Django 3.2.6 on 2021-08-21 20:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('user_id', models.TextField(verbose_name='user_id')),
                ('type', models.TextField(choices=[('in_progress', 'in_progress'), ('paid', 'paid')], verbose_name='type')),
                ('payment_method', models.TextField(verbose_name='payment_method')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': '"subscription"."order"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(verbose_name='name')),
                ('period', models.DurationField(verbose_name='period')),
                ('price', models.BigIntegerField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': '"subscription"."sub"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sub_film_work',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'verbose_name': 'sub_film_work',
                'verbose_name_plural': 'sub_film_works',
                'db_table': '"subscription"."sub_film_work"',
                'managed': False,
            },
        ),
    ]
