# Generated by Django 3.1 on 2020-10-07 08:57

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FilmWork',
            fields=[
                (
                    'id',
                    models.TextField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name='универсальный идентификатор',
                    ),
                ),
                ('title', models.TextField(verbose_name='заголовок')),
                (
                    'description',
                    models.TextField(blank=True, null=True, verbose_name='содержание'),
                ),
                (
                    'creation_date',
                    models.DateField(
                        blank=True, null=True, verbose_name='дата создания'
                    ),
                ),
                (
                    'certificate',
                    models.TextField(
                        blank=True, null=True, verbose_name='возрастной ценз'
                    ),
                ),
                (
                    'file_path',
                    models.TextField(blank=True, null=True, verbose_name='файл'),
                ),
                (
                    'rating',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name='рейтинг',
                    ),
                ),
                ('type', models.TextField(verbose_name='тип кинокартины')),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name='дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name='дата обновления'
                    ),
                ),
            ],
            options={
                'verbose_name': 'кинопроизведение',
                'verbose_name_plural': 'кинопроизведения',
                'db_table': '"content"."film_work"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                (
                    'id',
                    models.TextField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name='универсальный идентификатор',
                    ),
                ),
                ('name', models.TextField(verbose_name='название жанра')),
                (
                    'description',
                    models.TextField(blank=True, null=True, verbose_name='описание'),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name='дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name='дата обновления'
                    ),
                ),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
                'db_table': '"content"."genre"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenreFilmWork',
            fields=[
                (
                    'id',
                    models.TextField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={'db_table': '"content"."genre_film_work"', 'managed': False, },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                (
                    'id',
                    models.TextField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name='универсальный идентификатор',
                    ),
                ),
                ('name', models.TextField(verbose_name='имя')),
                ('surname', models.TextField(blank=True, verbose_name='фамилия')),
                (
                    'birth_date',
                    models.DateField(
                        blank=True, null=True, verbose_name='дата рождения'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name='дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name='дата обновления'
                    ),
                ),
            ],
            options={
                'verbose_name': 'человек',
                'verbose_name_plural': 'люди',
                'db_table': '"content"."person"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonFilmWork',
            fields=[
                (
                    'id',
                    models.TextField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ('role', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={'db_table': '"content"."person_film_work"', 'managed': False, },
        ),
    ]
