# Generated by Django 3.1 on 2020-10-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'managed': False,
                'proxy': True,
            },
            bases=('movies.filmwork',),
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
            ],
            options={
                'verbose_name': 'serial',
                'verbose_name_plural': 'serials',
                'managed': False,
                'proxy': True,
            },
            bases=('movies.filmwork',),
        ),
        migrations.AlterModelOptions(
            name='filmwork',
            options={'managed': False, 'verbose_name': 'film work', 'verbose_name_plural': 'film works'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'managed': False, 'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': False, 'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
    ]
